### ISSUE TITLE
when i run this below warning and not log in to Database

### ISSUE THREAD

**Issue by ArulMuruganChinnakannan** [nemanjapetrovic/mongoose-morgan#1]
Running on port 3000...
(node:12136) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

**Comment by nemanjapetrovic** [comment]
I will update all dependencies as soon as possible. Thank you!

**Comment by Dashue** [comment]
Bump?

**Comment by nemanjapetrovic** [comment]
@Dashue I'm waiting for information about the problem that is occurring with morgan dependency, here is an issue with more information: [morgan: issue 168 ](https://github.com/expressjs/morgan/issues/168)

As soon as I resolve the problem I'm having with morgan package I will update dependencies and resolve this issue we have.

Also, I added more unit tests for testing the whole logging so we could identify problems immediately with updated dependencies in the future.

**Comment by Dashue** [comment]
Cheers for the update and the link to more info!
This will simplify my life a lot, thanks for your effort.

**Comment by nemanjapetrovic** [comment]
@Dashue  
I updated this package to v1.0.5. Dependencies are now updated.
