### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by stijnpiron** [nemanjapetrovic/mongoose-morgan#10]
Hi,
Very happy with you package, makes life so much easier.
However, when moving to TypeScript now, TypeScript types would become handy as I have to manually override them at the moment with dirty fixes...
any plans of making them available in the future?

Thanks!

**Comment by nemanjapetrovic** [comment]
Hi @stijnpiron ,

Thank you for using this library and thank you for your kind words!

I will give my best to add TypeScript types over this weekend.

I will close the issue with the corresponding pull-req.

**Comment by nemanjapetrovic** [comment]
Ho @stijnpiron ,

I’ve just published v1.0.14 version of this library containing types for TypeScript. 

Can you please update your package and give it a try and let me know if everything is ok? 
Because I am not that much into TypeScript and maybe I’ve made a mistake somewhere.

**Comment by stijnpiron** [comment]
Hi @nemanjapetrovic 

Just gave it a testrun, looking good,
Thanks for that!

**Comment by nemanjapetrovic** [comment]
Hi @stijnpiron ,

you are welcome!

I will close down this issue.

BR,
Nemanja

**Comment by stijnpiron** [comment]
Hi @nemanjapetrovic,

Unfortunately I ran into an error. When using your types, I get this error on the express.Application.use function:

`No overload matches this call.
  The last overload gave the following error.
    Argument of type 'Object' is not assignable to parameter of type 'PathParams'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
          Type 'Object' is missing the following properties from type '(string | RegExp)[]': length, pop, push, concat, and 28 more.ts(2769)
index.d.ts(70, 5): The last overload is declared here.`

For the moment I can fix it by replacing `: Object` with `: any` in your types file.
Quick and dirty, but no final solution however ;-)

**Comment by nemanjapetrovic** [comment]
Hi @stijnpiron ,

I was thinking that i should go with ‘any’ and not ‘object’. I will reopen this issue and try to solve it by tomorrow. Thanks for reporting.

**Comment by nemanjapetrovic** [comment]
Hi @stijnpiron ,

I updated TypeScript types, please upgrade to v1.0.15 and give it a try. Let me know if this issue has been fixed?

**Comment by stijnpiron** [comment]
Hi @nemanjapetrovic 

Seems to be working now, thanks!
