### ISSUE TITLE
TypeError: morgan.token is not a function

### ISSUE THREAD

**Issue by mehtatejas** [nemanjapetrovic/mongoose-morgan#3]
I am trying to add token to morgan logs.
However, I am getting following error :
morgan.token("conversation-id", function getConversationId(req) {
       ^

TypeError: morgan.token is not a function

Kindly guide

**Comment by nemanjapetrovic** [comment]
@mehtatejas 

Sorry for late response, I have a hard time working on open source lately, I am trying...

I fixed this issue with v1.0.6 version of mongoose-morgan. Please try by updating version of your package.json mongoose-morgan dependency.

How will this work:
```
const mongooseMorgan = require('mongoose-morgan');

mongooseMorgan.token("conversation-id", function getConversationId(req) {
....
...
});

app.use(mongooseMorgan({
    connectionString: 'mongodb://localhost:27017/MongooseMorganUnit'
}, {}, 'short'));

....
```

**Comment by georgerussellpruitt** [comment]
I am experiencing this problem in version 1.0.8

**Comment by nemanjapetrovic** [comment]
@georgerussellpruitt 

I just tested this with v1.0.8 and I couldn't reproduce the problem, can you post here the code sample which reproduced the problem for you?

**Comment by p6297** [comment]
app.use(morgan(':method :url :status :res[content-length] - :response-time ms'))

just use this as  the middleware. 

please let me know if this is helpful to you
