### ISSUE TITLE
Deprecation Warning - useUnifiedTopology

### ISSUE THREAD

**Issue by trzcinskiD** [nemanjapetrovic/mongoose-morgan#8]
Hi,

Thank you for useful library. It really have saved my time.

Received this warning after implementation:

`DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

I suggest to add option in mongoData object with this parameter or to add rigidly this parameter in library code:

```    
mongoose.connect(mongoData.connectionString, {
        user: mongoData.user || null,
        pass: mongoData.pass || null,
        dbName: mongoData.dbName || null,
        useNewUrlParser: true,
        useUnifiedTopology: true
    });
```

**Comment by nemanjapetrovic** [comment]
Hi,

Thank you for your kind words, they really mean to me. I always tend to create something that will help the community and developers all over the world. :)

I will check it and add it as an additional parameter. Thank you a lot.

I will close this issue when the library is updated.

**Comment by nemanjapetrovic** [comment]
Hi,

An issue has been resolved. Please update your package.json dependency to the latest version of mongoose-morgan.

Thank you so much for reporting and supporting this library.
