### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by mrjleo198901** [nemanjapetrovic/mongoose-morgan#9]
Hi man, firstable good job!

So, The requests always are saved with GMT+0 time zone. I want to change this behavior adding to lines in the package. How can I create a pull request?

Regards,

Leonardo Munoz

**Comment by nemanjapetrovic** [comment]
Hi @mrjleo198901 ,

thank you! I always tend to support the community.

As for your question I suggest to check the following links:

https://mongoosejs.com/docs/tutorials/dates.html

https://stackoverflow.com/a/35672489

From Mongoose docs:

**Timezones**

MongoDB stores dates as 64-bit integers, which means that Mongoose does not store timezone information by default. When you call Date#toString(), the JavaScript runtime will use your OS' timezone.


So I guess you will have to change timezone on your server machine to adjust it for your needs.

I hope these links will help you.

Best regards,
Nemanja
